# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfc50d25f0855f0d16b6fca8d75d4196e4e0a7636ea04803e251a737c34b14fb595ac32c25f6faa8d6f959c17b2d28308ff896ccd751d8a129a5abc2479ba7e6

test:
  secret_key_base: 0c15f24a41a54e25190709f2c915ab96201e7959cd6e9109d79ea9860f0b5b9ca3a6e09e4ce83d97be12387b86ede45214d0317bf1a575340c2738a4a26412a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
